
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class AppointmentDetails extends javax.swing.JFrame {

    /**
     * Creates new form AppointmentDetails
     */
    public AppointmentDetails() {
        initComponents();
        jRadioButton1.setSelected(true);
         try{
            Class.forName("com.mysql.cj.jdbc.Driver");
        
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","");
        
            Statement st=con.createStatement(); 
            String query="select * from appointmentsdetails";
            ResultSet rs=st.executeQuery(query);
            ResultSetMetaData rsmd=rs.getMetaData();
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            
            int cols=rsmd.getColumnCount();
            String[] colname=new String[cols];
            for(int i=0;i<cols;i++){
                colname[i]=rsmd.getColumnName(i+1);
                model.setColumnIdentifiers(colname); 
            }
             String aid,did,pid,day,status;
             Double payment;
                while(rs.next()){
                    aid=rs.getString(1);
                    did=rs.getString(2);
                    pid=rs.getString(3);
                    day=rs.getString(4);
                    payment=rs.getDouble(5);
                    status=rs.getString(6);
                    

                    String strpay=String.valueOf(payment);
                    String[] row={ aid,did,pid,day,strpay,status};
                    model.addRow(row);
                    }
             st.close();
                con.close();
      
        }catch(Exception ex){
             JOptionPane.showMessageDialog(this, "Error occurred","Error",JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(720, 450));

        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Details");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Show Details");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jRadioButton1.setText("All");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jRadioButton2.setText("Pending");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jRadioButton3.setText("Done");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Mark as Completed");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Mark as Pending");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("Mark as Cancelled");
        jButton4.setActionCommand("Mark as Cancelled");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton2)
                        .addGap(29, 29, 29)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(114, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton3)
                        .addGap(178, 178, 178))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Homepage().show();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
         try{
             DefaultTableModel dm=(DefaultTableModel)jTable1.getModel();
              dm.getDataVector().removeAllElements();
              dm.fireTableDataChanged();
             
            Class.forName("com.mysql.cj.jdbc.Driver");
        
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","");
        
            Statement st=con.createStatement(); 
            String query="select * from appointmentsdetails";
            ResultSet rs=st.executeQuery(query);
            ResultSetMetaData rsmd=rs.getMetaData();
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            
            int cols=rsmd.getColumnCount();
            String[] colname=new String[cols];
            for(int i=0;i<cols;i++){
                colname[i]=rsmd.getColumnName(i+1);
                model.setColumnIdentifiers(colname); 
            }
             String aid,did,pid,day,status;
             Double payment;
                while(rs.next()){
                    aid=rs.getString(1);
                    did=rs.getString(2);
                    pid=rs.getString(3);
                    day=rs.getString(4);
                    payment=rs.getDouble(5);
                    status=rs.getString(6);
                    

                    String strpay=String.valueOf(payment);
                    String[] row={ aid,did,pid,day,strpay,status};
                    model.addRow(row);
                    }
             st.close();
                con.close();
      
        }catch(Exception ex){
             JOptionPane.showMessageDialog(this, "Error occurred","Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
         try{
             DefaultTableModel dm=(DefaultTableModel)jTable1.getModel();
              dm.getDataVector().removeAllElements();
              dm.fireTableDataChanged();
             
            Class.forName("com.mysql.cj.jdbc.Driver");
        
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","");
        
            Statement st=con.createStatement(); 
            String query="select * from appointmentsdetails where Status='pending'";
            ResultSet rs=st.executeQuery(query);
            ResultSetMetaData rsmd=rs.getMetaData();
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            
            int cols=rsmd.getColumnCount();
            String[] colname=new String[cols];
            for(int i=0;i<cols;i++){
                colname[i]=rsmd.getColumnName(i+1);
                model.setColumnIdentifiers(colname); 
            }
             String aid,did,pid,day,status;
             Double payment;
                while(rs.next()){
                    aid=rs.getString(1);
                    did=rs.getString(2);
                    pid=rs.getString(3);
                    day=rs.getString(4);
                    payment=rs.getDouble(5);
                    status=rs.getString(6);
                    

                    String strpay=String.valueOf(payment);
                    String[] row={ aid,did,pid,day,strpay,status};
                    model.addRow(row);
                    }
             st.close();
                con.close();
      
        }catch(Exception ex){
             JOptionPane.showMessageDialog(this, "Error occurred","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
         try{
             DefaultTableModel dm=(DefaultTableModel)jTable1.getModel();
              dm.getDataVector().removeAllElements();
              dm.fireTableDataChanged();
             
            Class.forName("com.mysql.cj.jdbc.Driver");
        
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","");
        
            Statement st=con.createStatement(); 
            String query="select * from appointmentsdetails where Status='completed'";
            ResultSet rs=st.executeQuery(query);
            ResultSetMetaData rsmd=rs.getMetaData();
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            
            int cols=rsmd.getColumnCount();
            String[] colname=new String[cols];
            for(int i=0;i<cols;i++){
                colname[i]=rsmd.getColumnName(i+1);
                model.setColumnIdentifiers(colname); 
            }
             String aid,did,pid,day,status;
             Double payment;
                while(rs.next()){
                    aid=rs.getString(1);
                    did=rs.getString(2);
                    pid=rs.getString(3);
                    day=rs.getString(4);
                    payment=rs.getDouble(5);
                    status=rs.getString(6);
                    

                    String strpay=String.valueOf(payment);
                    String[] row={ aid,did,pid,day,strpay,status};
                    model.addRow(row);
                    }
             st.close();
                con.close();
      
        }catch(Exception ex){
             JOptionPane.showMessageDialog(this, "Error occurred","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          try{
        int row=jTable1.getSelectedRow();
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        
        String selected=model.getValueAt(row,0).toString();
         if(row>=0){
             model.removeRow(row);
             
               Class.forName("com.mysql.cj.jdbc.Driver");
        
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","");
               PreparedStatement ps=con.prepareStatement("Update appointmentsdetails set Status='completed' where AppointmentID='"+selected+"' ");
              ps.executeUpdate();

         }
       }catch(Exception ex){
         JOptionPane.showMessageDialog(this, "Error occurred","Error",JOptionPane.ERROR_MESSAGE);

       }
           try{
                DefaultTableModel dm=(DefaultTableModel)jTable1.getModel();
              dm.getDataVector().removeAllElements();
              dm.fireTableDataChanged();
               
            Class.forName("com.mysql.cj.jdbc.Driver");
        
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","");
        
            Statement st=con.createStatement(); 
            String query="select * from appointmentsdetails";
            ResultSet rs=st.executeQuery(query);
            ResultSetMetaData rsmd=rs.getMetaData();
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            
            int cols=rsmd.getColumnCount();
            String[] colname=new String[cols];
            for(int i=0;i<cols;i++){
                colname[i]=rsmd.getColumnName(i+1);
                model.setColumnIdentifiers(colname); 
            }
             String aid,did,pid,day,status;
             Double payment;
                while(rs.next()){
                    aid=rs.getString(1);
                    did=rs.getString(2);
                    pid=rs.getString(3);
                    day=rs.getString(4);
                    payment=rs.getDouble(5);
                    status=rs.getString(6);
                    

                    String strpay=String.valueOf(payment);
                    String[] row={ aid,did,pid,day,strpay,status};
                    model.addRow(row);
                    }
             st.close();
                con.close();
      
        }catch(Exception ex){
             JOptionPane.showMessageDialog(this, "Error occurred","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
           try{
        int row=jTable1.getSelectedRow();
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        
        String selected=model.getValueAt(row,0).toString();
         if(row>=0){
             model.removeRow(row);
             
               Class.forName("com.mysql.cj.jdbc.Driver");
        
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","");
               PreparedStatement ps=con.prepareStatement("Update appointmentsdetails set Status='pending' where AppointmentID='"+selected+"' ");
              ps.executeUpdate();

         }
       }catch(Exception ex){
         JOptionPane.showMessageDialog(this, "Error occurred","Error",JOptionPane.ERROR_MESSAGE);

       }
           
            try{
                 DefaultTableModel dm=(DefaultTableModel)jTable1.getModel();
              dm.getDataVector().removeAllElements();
              dm.fireTableDataChanged();
                
            Class.forName("com.mysql.cj.jdbc.Driver");
        
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","");
        
            Statement st=con.createStatement(); 
            String query="select * from appointmentsdetails";
            ResultSet rs=st.executeQuery(query);
            ResultSetMetaData rsmd=rs.getMetaData();
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            
            int cols=rsmd.getColumnCount();
            String[] colname=new String[cols];
            for(int i=0;i<cols;i++){
                colname[i]=rsmd.getColumnName(i+1);
                model.setColumnIdentifiers(colname); 
            }
             String aid,did,pid,day,status;
             Double payment;
                while(rs.next()){
                    aid=rs.getString(1);
                    did=rs.getString(2);
                    pid=rs.getString(3);
                    day=rs.getString(4);
                    payment=rs.getDouble(5);
                    status=rs.getString(6);
                    

                    String strpay=String.valueOf(payment);
                    String[] row={ aid,did,pid,day,strpay,status};
                    model.addRow(row);
                    }
             st.close();
                con.close();
      
        }catch(Exception ex){
             JOptionPane.showMessageDialog(this, "Error occurred","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          try{
        int row=jTable1.getSelectedRow();
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        
        String selected=model.getValueAt(row,0).toString();
         if(row>=0){
             model.removeRow(row);
             
               Class.forName("com.mysql.cj.jdbc.Driver");
        
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","");
               PreparedStatement ps=con.prepareStatement("Update appointmentsdetails set Status='cancelled' where AppointmentID='"+selected+"' ");
              ps.executeUpdate();

         }
       }catch(Exception ex){
         JOptionPane.showMessageDialog(this, "Error occurred","Error",JOptionPane.ERROR_MESSAGE);

       }
           
            try{
                 DefaultTableModel dm=(DefaultTableModel)jTable1.getModel();
              dm.getDataVector().removeAllElements();
              dm.fireTableDataChanged();
                
            Class.forName("com.mysql.cj.jdbc.Driver");
        
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","");
        
            Statement st=con.createStatement(); 
            String query="select * from appointmentsdetails";
            ResultSet rs=st.executeQuery(query);
            ResultSetMetaData rsmd=rs.getMetaData();
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            
            int cols=rsmd.getColumnCount();
            String[] colname=new String[cols];
            for(int i=0;i<cols;i++){
                colname[i]=rsmd.getColumnName(i+1);
                model.setColumnIdentifiers(colname); 
            }
             String aid,did,pid,day,status;
             Double payment;
                while(rs.next()){
                    aid=rs.getString(1);
                    did=rs.getString(2);
                    pid=rs.getString(3);
                    day=rs.getString(4);
                    payment=rs.getDouble(5);
                    status=rs.getString(6);
                    

                    String strpay=String.valueOf(payment);
                    String[] row={ aid,did,pid,day,strpay,status};
                    model.addRow(row);
                    }
             st.close();
                con.close();
      
        }catch(Exception ex){
             JOptionPane.showMessageDialog(this, "Error occurred","Error",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 String src="com.jtattoo.plaf.hifi.HiFiLookAndFeel";
                try {
                    UIManager.setLookAndFeel(src);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                new AppointmentDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
